apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 337191499127.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 337191499127.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: acce62b7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
